-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Värd: localhost
-- Tid vid skapande: 03 apr 2024 kl 22:42
-- Serverversion: 10.4.28-MariaDB
-- PHP-version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Databas: `pilk-radio`
--

-- --------------------------------------------------------

--
-- Tabellstruktur `music`
--

CREATE TABLE `music` (
  `id` int(11) NOT NULL,
  `title` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `producer` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `producer_url` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `source_url` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `last_played` timestamp NOT NULL DEFAULT current_timestamp(),
  `music_path` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `playing` tinyint(1) NOT NULL DEFAULT 0,
  `length` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Dumpning av Data i tabell `music`
--

INSERT INTO `music` (`id`, `title`, `producer`, `producer_url`, `source_url`, `last_played`, `music_path`, `playing`, `length`) VALUES
(323, 'Neco Arc - Berserk Forces [ AI Cover ]', 'christang', 'https://www.youtube.com/@christangTheOne', 'https://www.youtube.com/watch?v=M7jhewKTx3M', '2024-04-01 22:00:00', './music/Neco Arc - Berserk Forces [ AI Cover ]-christang.opus', 0, 239),
(324, 'I Wonder - Neco arc x Kyne West', 'Froppy Randomness', 'https://www.youtube.com/@FroppyRandomness', 'https://www.youtube.com/watch?v=XajJgBY0AOs', '2024-04-01 22:00:00', './music/I Wonder - Neco arc x Kyne West-Froppy Randomness.opus', 0, 246),
(326, 'Lil Neco Arc - Old Town Cat (Neco Arc AI Cover) ft. Freddie Mercury', 'FliKer', 'https://www.youtube.com/@fl1ktm', 'https://www.youtube.com/watch?v=cCiqEKynwcA', '2024-04-01 22:00:00', './music/Lil Neco Arc - Old Town Cat (Neco Arc AI Cover) ft. Freddie Mercury-FliKer.opus', 0, 158),
(327, 'Neco Arc - МАСЮНЯ (AI COVER)', 'Дима Mojong', 'https://www.youtube.com/@TheMojongChannel', 'https://www.youtube.com/watch?v=0tbEyj55hPQ', '2024-04-01 22:00:00', './music/Neco Arc - МАСЮНЯ (AI COVER)-Дима Mojong.opus', 0, 144),
(328, 'Neco Arc - Tick Tock (Joji Cover)', 'Kip', 'https://www.youtube.com/@Kippuin', 'https://www.youtube.com/watch?v=6Rv5oGzJnBs', '2024-04-01 22:00:00', './music/Neco Arc - Tick Tock (Joji Cover)-Kip.opus', 0, 132),
(329, 'Neco Arc - Stigmata - Сентябрь (AI Cover)', 'rsdelta', 'https://www.youtube.com/@rsdelta', 'https://www.youtube.com/watch?v=kz0IDgUWMo4', '2024-04-01 22:00:00', './music/Neco Arc - Stigmata - Сентябрь (AI Cover)-rsdelta.opus', 0, 242),
(330, 'Neco Arc - Белая ночь [ Ai Cover ]', 'LazyKat', 'https://www.youtube.com/@LazyKoten', 'https://www.youtube.com/watch?v=dc37kHXiaBE', '2024-04-01 22:00:00', './music/Neco Arc - Белая ночь [ Ai Cover ]-LazyKat.opus', 0, 239),
(331, 'Молчат НекоАрк – Судnya | Молчат дома - Судно Neco-Arc (AI Cover)', 'Stinky freaks', 'https://www.youtube.com/@Stinkyfreaks', 'https://www.youtube.com/watch?v=1VawjUuAccI', '2024-04-01 22:00:00', './music/Молчат НекоАрк – Судnya | Молчат дома - Судно Neco-Arc (AI Cover)-Stinky freaks.opus', 0, 144),
(332, 'Neco Arc-In the End Linkin Park', 'ShiroUDrak', 'https://www.youtube.com/@ShiroDrao', 'https://www.youtube.com/watch?v=U1zDp9923PU', '2024-04-01 22:00:00', './music/Neco Arc-In the End Linkin Park-ShiroUDrak.opus', 0, 218),
(333, 'Neco Arc - Gorillaz - Clint Eastwood (AI Cover)', 'rsdelta', 'https://www.youtube.com/@rsdelta', 'https://www.youtube.com/watch?v=8W4HLWTHwa8', '2024-04-01 22:00:00', './music/Neco Arc - Gorillaz - Clint Eastwood (AI Cover)-rsdelta.opus', 0, 251),
(334, 'Neco Arc - Feel Good Inc. (AI Cover)', 'Honchu', 'https://www.youtube.com/@Honchu1', 'https://www.youtube.com/watch?v=1KBszSo-lJo', '2024-04-01 22:00:00', './music/Neco Arc - Feel Good Inc. (AI Cover)-Honchu.opus', 0, 222),
(335, 'Neco Arc - Scatmans World (AI Cover)', 'rsdelta', 'https://www.youtube.com/@rsdelta', 'https://www.youtube.com/watch?v=KFpuPFPD8lQ', '2024-04-01 22:00:00', './music/Neco Arc - Scatmans World (AI Cover)-rsdelta.opus', 0, 222),
(336, 'Neco Arc Linkin Park  What Ive Done (I.A)Cover', 'ShiroUDrak', 'https://www.youtube.com/@ShiroDrao', 'https://www.youtube.com/watch?v=SrAA_h5Ze10', '2024-04-01 22:00:00', './music/Neco Arc Linkin Park  What Ive Done (I.A)Cover-ShiroUDrak.opus', 0, 205),
(337, 'Skillet - Monster, but Neco Arc sings it (AI COVER)', 'Xylopho', 'https://www.youtube.com/@Xylopho_AI', 'https://www.youtube.com/watch?v=NdgWUeylzQk', '2024-04-01 22:00:00', './music/Skillet - Monster, but Neco Arc sings it (AI COVER)-Xylopho.opus', 0, 177),
(338, 'Tu falta de querer - Neco-arc AI cover', 'Necovers-Arc', 'https://www.youtube.com/@Necovers-arc', 'https://www.youtube.com/watch?v=M_TDPFZd530', '2024-04-01 22:00:00', './music/Tu falta de querer - Neco-arc AI cover-Necovers-Arc.opus', 0, 278),
(339, 'Seven - Neco-arc AI cover', 'Necovers-Arc', 'https://www.youtube.com/@Necovers-arc', 'https://www.youtube.com/watch?v=rj_UlkKmuQo', '2024-04-01 22:00:00', './music/Seven - Neco-arc AI cover-Necovers-Arc.opus', 0, 286),
(340, 'Neco Arc - Бесприданница (Neco Arc AI Cover)', 'FliKer', 'https://www.youtube.com/@fl1ktm', 'https://www.youtube.com/watch?v=L2sd6yhWcWQ', '2024-04-01 22:00:00', './music/Neco Arc - Бесприданница (Neco Arc AI Cover)-FliKer.opus', 0, 163),
(341, 'Neco Arc - Disturbed - Decadence (Neco Arc AI Cover', 'FliKer', 'https://www.youtube.com/@fl1ktm', 'https://www.youtube.com/watch?v=UAh44gOz1FA', '2024-04-01 22:00:00', './music/Neco Arc - Disturbed - Decadence (Neco Arc AI Cover-FliKer.opus', 0, 198),
(342, 'Neco Arc - Bring me to life cover', 'lessthanthree', 'https://www.youtube.com/@kapono_', 'https://www.youtube.com/watch?v=E-krWpqPWRE', '2024-04-01 22:00:00', './music/Neco Arc - Bring me to life cover-lessthanthree.opus', 0, 237),
(343, 'Neco Arc-Fly Me To The Moon', 'La-Creatura', 'https://www.youtube.com/@La-Creatura', 'https://www.youtube.com/watch?v=YzYdM0nUkTQ', '2024-04-01 22:00:00', './music/Neco Arc-Fly Me To The Moon-La-Creatura.opus', 0, 148),
(344, 'The real slim kittie (Neco arc slim shady AI cover)', 'Demonmask', 'https://www.youtube.com/@Demonmask-whatareyoulookingat', 'https://www.youtube.com/watch?v=u1kX9IH2dik', '2024-04-01 22:00:00', './music/The real slim kittie (Neco arc slim shady AI cover)-Demonmask.opus', 0, 268),
(345, 'Neco Arc - Падать в Грязь (AI Cover)', 'FliKer', 'https://www.youtube.com/@fl1ktm', 'https://www.youtube.com/watch?v=BMI_dpNU-0A', '2024-04-01 22:00:00', './music/Neco Arc - Падать в Грязь (AI Cover)-FliKer.opus', 0, 165),
(346, 'Neco Arc, Hatsune Miku - Я Сошла С Ума (AI Cover)', 'FliKer', 'https://www.youtube.com/@fl1ktm', 'https://www.youtube.com/watch?v=t6cke73zwv4', '2024-04-01 22:00:00', './music/Neco Arc, Hatsune Miku - Я Сошла С Ума (AI Cover)-FliKer.opus', 0, 225),
(347, 'Neco Arc -  Holiday   Boulevard of Broken Dreams (Green Day Cover)', 'Kip', 'https://www.youtube.com/@Kippuin', 'https://www.youtube.com/watch?v=2cPuvqYDz_Y', '2024-04-01 22:00:00', './music/Neco Arc -  Holiday   Boulevard of Broken Dreams (Green Day Cover)-Kip.opus', 0, 494),
(348, 'Neco Arc - Wake Me Up When September Ends (AI Cover)', 'rsdelta', 'https://www.youtube.com/@rsdelta', 'https://www.youtube.com/watch?v=7_2w6rL2f2w', '2024-04-01 22:00:00', './music/Neco Arc - Wake Me Up When September Ends (AI Cover)-rsdelta.opus', 0, 275),
(349, 'Neco Arc - All Star (Smash Mouth Cover)', 'Kip', 'https://www.youtube.com/@Kippuin', 'https://www.youtube.com/watch?v=nJFkl1O0358', '2024-04-01 22:00:00', './music/Neco Arc - All Star (Smash Mouth Cover)-Kip.opus', 0, 201),
(350, 'Neco Arc - Tokyo Cat (Neco Arc AI Cover)', 'FliKer', 'https://www.youtube.com/@fl1ktm', 'https://www.youtube.com/watch?v=k9o4WR58NdI', '2024-04-01 22:00:00', './music/Neco Arc - Tokyo Cat (Neco Arc AI Cover)-FliKer.opus', 0, 90),
(351, 'Neco Arc - Great War (ai cover)', 'Encrypted Lobster', 'https://www.youtube.com/@encryptedlobster', 'https://www.youtube.com/watch?v=cw48q-3LY24', '2024-04-01 22:00:00', './music/Neco Arc - Great War (ai cover)-Encrypted Lobster.opus', 0, 269),
(352, '【-Neko Arc -Kanaria】KING Cover A.i    !Warning Epilepcia Ligera!', 'ShiroUDrak', 'https://www.youtube.com/@ShiroDrao', 'https://www.youtube.com/watch?v=49aWG3fA1tM', '2024-04-01 22:00:00', './music/【-Neko Arc -Kanaria】KING Cover A.i    !Warning Epilepcia Ligera!-ShiroUDrak.opus', 0, 136),
(353, 'Neco Arc - Godzilla (Eminem Cover) Ft. Neco Arc Chaos', 'Kip', 'https://www.youtube.com/@Kippuin', 'https://www.youtube.com/watch?v=RD4oOwkhAss', '2024-04-01 22:00:00', './music/Neco Arc - Godzilla (Eminem Cover) Ft. Neco Arc Chaos-Kip.opus', 0, 213),
(354, 'Neco Arc - Lucid Dreams [AI Cover]', 'Nesqquick2', 'https://www.youtube.com/@Nesqquick2', 'https://www.youtube.com/watch?v=T98jM6AojW4', '2024-04-01 22:00:00', './music/Neco Arc - Lucid Dreams [AI Cover]-Nesqquick2.opus', 0, 240),
(355, 'Neco arc Hope XXXTENTACION AI cover', 'Blunt', 'https://www.youtube.com/@Bluntttttt', 'https://www.youtube.com/watch?v=kshQqS1wiHw', '2024-04-01 22:00:00', './music/Neco arc Hope XXXTENTACION AI cover-Blunt.opus', 0, 111),
(356, 'moonlight neco arc ai cover', 'Archareux', 'https://www.youtube.com/@archareux', 'https://www.youtube.com/watch?v=i_aOKWTfNG8', '2024-04-01 22:00:00', './music/moonlight neco arc ai cover-Archareux.opus', 0, 140),
(357, 'Neco Arc - XO Tour Llif3 || AI Cover', 'ItzChuChu', 'https://www.youtube.com/@ItzChuChu_', 'https://www.youtube.com/watch?v=1eCth2viaB0', '2024-04-01 22:00:00', './music/Neco Arc - XO Tour Llif3 || AI Cover-ItzChuChu.opus', 0, 179),
(358, 'Lalala - Neco-arc AI cover', 'Necovers-Arc', 'https://www.youtube.com/@Necovers-arc', 'https://www.youtube.com/watch?v=lu-m6dEfHr8', '2024-04-01 22:00:00', './music/Lalala - Neco-arc AI cover-Necovers-Arc.opus', 0, 161),
(359, 'Neco Arc - Baby One More Time || AI Cover', 'ItzChuChu', 'https://www.youtube.com/@ItzChuChu_', 'https://www.youtube.com/watch?v=cCydA9F8kvA', '2024-04-01 22:00:00', './music/Neco Arc - Baby One More Time || AI Cover-ItzChuChu.opus', 0, 211),
(360, 'Neco Arc - Eye of the Tiger [AI Cover]', 'Nesqquick2', 'https://www.youtube.com/@Nesqquick2', 'https://www.youtube.com/watch?v=ez32JvpPoJE', '2024-04-01 22:00:00', './music/Neco Arc - Eye of the Tiger [AI Cover]-Nesqquick2.opus', 0, 244),
(361, 'Neco Arc - Закрой за мной дверь (Neco Arc AI Cover)', 'FliKer', 'https://www.youtube.com/@fl1ktm', 'https://www.youtube.com/watch?v=ZAPbNAoT1Dg', '2024-04-01 22:00:00', './music/Neco Arc - Закрой за мной дверь (Neco Arc AI Cover)-FliKer.opus', 0, 253),
(363, 'Blondie — Call me [Neco Arc AI Cover]', 'Saymon MacGregor', 'https://www.youtube.com/@saymonfromhell', 'https://www.youtube.com/watch?v=LOtm810lzcs', '2024-04-01 22:00:00', './music/Blondie — Call me [Neco Arc AI Cover]-Saymon MacGregor.opus', 0, 212),
(364, 'Neco Arc - Tokyo Drift (AI cover)', 'HIDDEN', 'https://www.youtube.com/@hidden457', 'https://www.youtube.com/watch?v=sIn4_TKRqCY', '2024-04-01 22:00:00', './music/Neco Arc - Tokyo Drift (AI cover)-HIDDEN.opus', 0, 255),
(365, 'Neco Arc - Modern Talking - Cheri Cheri Lady (AI Cover)', 'rsdelta', 'https://www.youtube.com/@rsdelta', 'https://www.youtube.com/watch?v=10uQ3hzAaww', '2024-04-01 22:00:00', './music/Neco Arc - Modern Talking - Cheri Cheri Lady (AI Cover)-rsdelta.opus', 0, 197),
(366, 'Neco Arc - Кончится лето (AI Cover)', 'Паша Лайвер', 'https://www.youtube.com/@Pasha_Lajver', 'https://www.youtube.com/watch?v=fZNBX2vyEDQ', '2024-04-01 22:00:00', './music/Neco Arc - Кончится лето (AI Cover)-Паша Лайвер.opus', 0, 285),
(367, 'Duvet by Bôa - Neco Arc Cover (AI Voice)', 'JellyPuff', 'https://www.youtube.com/@jellypuff7026', 'https://www.youtube.com/watch?v=c_fZNDjRp5Q', '2024-04-01 22:00:00', './music/Duvet by Bôa - Neco Arc Cover (AI Voice)-JellyPuff.opus', 0, 203),
(368, 'neco-arc sings stronger then you (500 Subs special)', 'Sokar', 'https://www.youtube.com/@MentalIllBoy', 'https://www.youtube.com/watch?v=eqFffQL8bXQ', '2024-04-01 22:00:00', './music/neco-arc sings stronger then you (500 Subs special)-Sokar.opus', 0, 171),
(369, 'Neco Arc - I got a glock in my rari (679) [ AI Cover ]', 'christang', 'https://www.youtube.com/@christangTheOne', 'https://www.youtube.com/watch?v=JQZyL2amu4E', '2024-04-01 22:00:00', './music/Neco Arc - I got a glock in my rari (679) [ AI Cover ]-christang.opus', 0, 197),
(370, 'Neco Arc - Boom, Boom, Boom, Boom!! [ AI Cover ]', 'just josh xd', 'https://www.youtube.com/@justjoshxd', 'https://www.youtube.com/watch?v=DHXBfA0Ryzk', '2024-04-01 22:00:00', './music/Neco Arc - Boom, Boom, Boom, Boom!! [ AI Cover ]-just josh xd.opus', 0, 206),
(371, 'Creeper oh man but neco arc and neco arc chaos sing it (AI cover)', 'Sokar', 'https://www.youtube.com/@MentalIllBoy', 'https://www.youtube.com/watch?v=u2BmpGktIa0', '2024-04-01 22:00:00', './music/Creeper oh man but neco arc and neco arc chaos sing it (AI cover)-Sokar.opus', 0, 221),
(372, 'Enamorado Tuyo - Neco-arc (Ia cover)', 'fernallen303', 'https://www.youtube.com/@fernallen303', 'https://www.youtube.com/watch?v=cAxuC_coLdk', '2024-04-01 22:00:00', './music/Enamorado Tuyo - Neco-arc (Ia cover)-fernallen303.opus', 0, 253),
(373, 'Sweet Little Bumblebee - Neco Arc (BEST AI VERSION)', 'Floofile', 'https://www.youtube.com/@floofile4873', 'https://www.youtube.com/watch?v=QVmPeKAY9LQ', '2024-04-01 22:00:00', './music/Sweet Little Bumblebee - Neco Arc (BEST AI VERSION)-Floofile.opus', 0, 197),
(375, 'Lemon Tree - Neco Arc (AI Cover)', 'Steffen', 'https://www.youtube.com/@steffenxyz', 'https://www.youtube.com/watch?v=YMRfallY1mc', '2024-04-01 22:00:00', './music/Lemon Tree - Neco Arc (AI Cover)-Steffen.opus', 0, 233),
(376, 'Neco Arc - Dragostea Din Tei   Numa Numa [ AI Cover ]', 'just josh xd', 'https://www.youtube.com/@justjoshxd', 'https://www.youtube.com/watch?v=_saqLyXogkQ', '2024-04-01 22:00:00', './music/Neco Arc - Dragostea Din Tei   Numa Numa [ AI Cover ]-just josh xd.opus', 0, 218),
(378, 'Neco Arc - Young Girl A   少女A [AI cover]', 'KanareyDiBud', 'https://www.youtube.com/@kanareydibud', 'https://www.youtube.com/watch?v=KxVDP6Zseko', '2024-04-01 22:00:00', './music/Neco Arc - Young Girl A   少女A [AI cover]-KanareyDiBud.opus', 0, 242),
(379, 'Polish cow - Neco Arc (AI Cover)', 'edwcz2', 'https://www.youtube.com/@edwcz2753', 'https://www.youtube.com/watch?v=CTNKBuklUHM', '2024-04-01 22:00:00', './music/Polish cow - Neco Arc (AI Cover)-edwcz2.opus', 0, 223),
(380, 'Neco of an Arc - Toxicity', 'Syngrafer', 'https://www.youtube.com/@Syngrafer', 'https://www.youtube.com/watch?v=qnJ0EcCeQjQ', '2024-04-01 22:00:00', './music/Neco of an Arc - Toxicity-Syngrafer.opus', 0, 225),
(381, 'Neco Arc - What Im Made Of (Sonic Heroes AI Cover)', 'Honchu', 'https://www.youtube.com/@Honchu1', 'https://www.youtube.com/watch?v=c0lvbd1hjuc', '2024-04-01 22:00:00', './music/Neco Arc - What Im Made Of (Sonic Heroes AI Cover)-Honchu.opus', 0, 222),
(382, 'The Offspring - Youre Gonna Go Far, Kid | Neco Arc (AI Cover)', 'Jolitrub', 'https://www.youtube.com/@jolitrub', 'https://www.youtube.com/watch?v=8_kA9d1_gTk', '2024-04-01 22:00:00', './music/The Offspring - Youre Gonna Go Far, Kid | Neco Arc (AI Cover)-Jolitrub.opus', 0, 179),
(383, 'Neco Arc - Fallen Kingdom (BEST AI COVER)', 'Floofile', 'https://www.youtube.com/@floofile4873', 'https://www.youtube.com/watch?v=OS3s_fKfhKg', '2024-04-01 22:00:00', './music/Neco Arc - Fallen Kingdom (BEST AI COVER)-Floofile.opus', 0, 288),
(384, 'Neco Arc - Stronger (Kanye West) [AI Cover]', 'houndlemon', 'https://www.youtube.com/@houndlemon', 'https://www.youtube.com/watch?v=dObi2jgwUkQ', '2024-04-01 22:00:00', './music/Neco Arc - Stronger (Kanye West) [AI Cover]-houndlemon.opus', 0, 312),
(386, 'Ms. Neco Arc - After Dark AI Cover', 'Abdllah Raphel', 'https://www.youtube.com/@AbdllahRaphel', 'https://www.youtube.com/watch?v=bMpZHpqBgCE', '2024-04-01 22:00:00', './music/Ms. Neco Arc - After Dark AI Cover-Abdllah Raphel.opus', 0, 262),
(387, 'Neco-Arc and Neco-Arc Chaos sing \"Barbie Girl\"', 'l1minal', 'https://www.youtube.com/@l1minal541', 'https://www.youtube.com/watch?v=_SKobMy5OkU', '2024-04-01 22:00:00', './music/Neco-Arc and Neco-Arc Chaos sing \"Barbie Girl\"-l1minal.opus', 0, 196),
(388, 'Neco Arc Sings Balling (Burger king edtion)', 'KaT_', 'https://www.youtube.com/@Katxkuna', 'https://www.youtube.com/watch?v=aLxjt1Cmvdc', '2024-04-01 22:00:00', './music/Neco Arc Sings Balling (Burger king edtion)-KaT_.opus', 0, 101),
(389, 'Neco Arc - Sonne (Rammstein AI Cover)', 'Xle8 - КолобКот', 'https://www.youtube.com/@xle8_off', 'https://www.youtube.com/watch?v=RcCy8gA_04Q', '2024-04-01 22:00:00', './music/Neco Arc - Sonne (Rammstein AI Cover)-Xle8 - КолобКот.opus', 0, 274),
(390, 'Neco Arc - Säkkijärven polkka (AI Cover)', 'Rhusakko', 'https://www.youtube.com/@Rhusakko', 'https://www.youtube.com/watch?v=E3TgzsFbCPk', '2024-04-01 22:00:00', './music/Neco Arc - Säkkijärven polkka (AI Cover)-Rhusakko.opus', 0, 140),
(391, 'Neco Arc - Every Time We Touch (Ai Cover)', 'Bugbzyyz', 'https://www.youtube.com/@Bugbzyyx', 'https://www.youtube.com/watch?v=60J_1MsXmus', '2024-04-01 22:00:00', './music/Neco Arc - Every Time We Touch (Ai Cover)-Bugbzyyz.opus', 0, 197),
(392, 'Neco Arc - Lost Kitten [ AI Cover ]', 'christang', 'https://www.youtube.com/@christangTheOne', 'https://www.youtube.com/watch?v=1PIyfaMyxMk', '2024-04-01 22:00:00', './music/Neco Arc - Lost Kitten [ AI Cover ]-christang.opus', 0, 197),
(393, 'Neco Arc - Panzerkampf (ai cover)', 'Encrypted Lobster', 'https://www.youtube.com/@encryptedlobster', 'https://www.youtube.com/watch?v=Boo2hK4FD4s', '2024-04-01 22:00:00', './music/Neco Arc - Panzerkampf (ai cover)-Encrypted Lobster.opus', 0, 312),
(394, 'Neco Arc -Lose Yourself', 'La-Creatura', 'https://www.youtube.com/@La-Creatura', 'https://www.youtube.com/watch?v=JAjSnYbpRFs', '2024-04-01 22:00:00', './music/Neco Arc -Lose Yourself-La-Creatura.opus', 0, 328),
(395, 'Neco Arc - Believer [AI COVER]', 'The Chop', 'https://www.youtube.com/@TheChopChannel', 'https://www.youtube.com/watch?v=-3Khlu_LeZo', '2024-04-01 22:00:00', './music/Neco Arc - Believer [AI COVER]-The Chop.opus', 0, 204),
(396, 'A thousand miles - neco arc ai cover', 'Kresigg', 'https://www.youtube.com/@Kresigg', 'https://www.youtube.com/watch?v=8vlNqePYGss', '2024-04-01 22:00:00', './music/A thousand miles - neco arc ai cover-Kresigg.opus', 0, 238),
(397, 'Three Days Grace - Animal I Have Become, but Neco Arc sings it (AI COVER)', 'Xylopho', 'https://www.youtube.com/@Xylopho_AI', 'https://www.youtube.com/watch?v=M_9niVsuPdg', '2024-04-01 22:00:00', './music/Three Days Grace - Animal I Have Become, but Neco Arc sings it (AI COVER)-Xylopho.opus', 0, 230),
(398, 'Neco Arc - Ruler of Everything (Tally Hall Cover)', 'Kip', 'https://www.youtube.com/@Kippuin', 'https://www.youtube.com/watch?v=-AOh_4DgXKg', '2024-04-01 22:00:00', './music/Neco Arc - Ruler of Everything (Tally Hall Cover)-Kip.opus', 0, 224),
(399, 'Neco Arc (A.I) Cover Fall Out Boy - Immortals', 'ShiroUDrak', 'https://www.youtube.com/@ShiroDrao', 'https://www.youtube.com/watch?v=LAs4hXSgRo0', '2024-04-01 22:00:00', './music/Neco Arc (A.I) Cover Fall Out Boy - Immortals-ShiroUDrak.opus', 0, 200),
(400, 'Zombies On Your Lawn - Neco Arc AI Cover', 'rami', 'https://www.youtube.com/@ramielzs', 'https://www.youtube.com/watch?v=ZIaEgcv-Mzk', '2024-04-01 22:00:00', './music/Zombies On Your Lawn - Neco Arc AI Cover-rami.opus', 0, 159),
(401, 'If we ever broke up || Neko arc cover AI', 'Mozzballs', 'https://www.youtube.com/@Mozzballs', 'https://www.youtube.com/watch?v=ItnnEtWGJ-g', '2024-04-01 22:00:00', './music/If we ever broke up || Neko arc cover AI-Mozzballs.opus', 0, 145),
(402, 'Neco arc sings After Dark (ai cover)', 'The cat', 'https://www.youtube.com/@thecat5801', 'https://www.youtube.com/watch?v=G6uyhbV2mXI', '2024-04-01 22:00:00', './music/Neco arc sings After Dark (ai cover)-The cat.opus', 0, 257),
(403, 'Neco arc - Sunflower [Ai Cover]', 'Nomadism', 'https://www.youtube.com/@nomadyesmad', 'https://www.youtube.com/watch?v=OyDD1I9CPsU', '2024-04-01 22:00:00', './music/Neco arc - Sunflower [Ai Cover]-Nomadism.opus', 0, 158),
(404, 'Gorillaz - 19-2000 (Neco Arc AI Cover)', 'Mtseng', 'https://www.youtube.com/@Senguha', 'https://www.youtube.com/watch?v=fP8RmPq5UTo', '2024-04-01 22:00:00', './music/Gorillaz - 19-2000 (Neco Arc AI Cover)-Mtseng.opus', 0, 208),
(405, 'OMORI OST - My Time (Neco Arc AI Cover)', 'Drixystix', 'https://www.youtube.com/@Drixystix', 'https://www.youtube.com/watch?v=hsd3gJIFa0M', '2024-04-01 22:00:00', './music/OMORI OST - My Time (Neco Arc AI Cover)-Drixystix.opus', 0, 213),
(406, 'Neco Arc - Camel By Camel [ AI Cover ]', 'christang', 'https://www.youtube.com/@christangTheOne', 'https://www.youtube.com/watch?v=4b-c39PRPsE', '2024-04-01 22:00:00', './music/Neco Arc - Camel By Camel [ AI Cover ]-christang.opus', 0, 356),
(407, 'Neco-Arc sings Buddy Holly (AI Cover)', 'Endergamer.mp4', 'https://www.youtube.com/@endergamer.mp4', 'https://www.youtube.com/watch?v=1a00BFfCOwE', '2024-04-01 22:00:00', './music/Neco-Arc sings Buddy Holly (AI Cover)-Endergamer.mp4.opus', 0, 163),
(408, 'Enej Skrzydlate Ręce - Neco-Arc [AI COVER]', 'mikolak14', 'https://www.youtube.com/@mikolak14', 'https://www.youtube.com/watch?v=QEVnKhAfHG4', '2024-04-01 22:00:00', './music/Enej Skrzydlate Ręce - Neco-Arc [AI COVER]-mikolak14.opus', 0, 187),
(410, 'Boom Boom Boom Boom - VengaBoys (Neco Arc AI Cover)', 'Cat587', 'https://www.youtube.com/@HotJoseph', 'https://www.youtube.com/watch?v=IcSquUbx0DA', '2024-04-01 22:00:00', './music/Boom Boom Boom Boom - VengaBoys (Neco Arc AI Cover)-Cat587.opus', 0, 205),
(411, 'Neco Arc - Super Idol [ AI Cover ]', 'christang', 'https://www.youtube.com/@christangTheOne', 'https://www.youtube.com/watch?v=yrxa3H_91vo', '2024-04-01 22:00:00', './music/Neco Arc - Super Idol [ AI Cover ]-christang.opus', 0, 197),
(413, 'Berserk OP - Tell My Why neco arc AI cover', 'Trole', 'https://www.youtube.com/@Trole.', 'https://www.youtube.com/watch?v=ryT9hZ_hYeY', '2024-04-01 22:00:00', './music/Berserk OP - Tell My Why neco arc AI cover-Trole.opus', 0, 70),
(414, 'Linkin Park - Faint (Neco Arc AI cover)', 'HorpasEn', 'https://www.youtube.com/@HorpasEn', 'https://www.youtube.com/watch?v=5qsPHhlJ6gs', '2024-04-01 22:00:00', './music/Linkin Park - Faint (Neco Arc AI cover)-HorpasEn.opus', 0, 162),
(415, 'Neco Arc - Life is a Highway (Rascal Flatts Cover)', 'Kip', 'https://www.youtube.com/@Kippuin', 'https://www.youtube.com/watch?v=SVNn6yQH7i8', '2024-04-01 22:00:00', './music/Neco Arc - Life is a Highway (Rascal Flatts Cover)-Kip.opus', 0, 279),
(416, 'I miss the old Neco Arc [ AI Cover ]', 'christang', 'https://www.youtube.com/@christangTheOne', 'https://www.youtube.com/watch?v=aGdQvNxpZ_I', '2024-04-01 22:00:00', './music/I miss the old Neco Arc [ AI Cover ]-christang.opus', 0, 124),
(417, 'Me voy - Neco-arc AI cover', 'Necovers-Arc', 'https://www.youtube.com/@Necovers-arc', 'https://www.youtube.com/watch?v=TCV4vOzSLLw', '2024-04-01 22:00:00', './music/Me voy - Neco-arc AI cover-Necovers-Arc.opus', 0, 188),
(418, 'Buranyality | Jamiroquai - Virtual Insanity Neco-Arc (AI Cover)', '0x0v3rfl0w', 'https://www.youtube.com/@0x0v3rfl0w', 'https://www.youtube.com/watch?v=AXjaf3tQ2So', '2024-04-01 22:00:00', './music/Buranyality | Jamiroquai - Virtual Insanity Neco-Arc (AI Cover)-0x0v3rfl0w.opus', 0, 229),
(419, 'Night Dancer (cover español) - Neco Arc AI cover', 'Agalo', 'https://www.youtube.com/@agalo724', 'https://www.youtube.com/watch?v=ZVTY128NMO0', '2024-04-01 22:00:00', './music/Night Dancer (cover español) - Neco Arc AI cover-Agalo.opus', 0, 212),
(420, 'Oh Shit Im Nyanning it - Neco Arc Ai Cover', 'R. Daneel Olviaw', 'https://www.youtube.com/@R.DaneelOlviaw', 'https://www.youtube.com/watch?v=_LOtT3CF1cA', '2024-04-01 22:00:00', './music/Oh Shit Im Nyanning it - Neco Arc Ai Cover-R. Daneel Olviaw.opus', 0, 215),
(421, 'Buddy Holly - Neco Arc [A.I. Cover]', 'La-Creatura', 'https://www.youtube.com/@La-Creatura', 'https://www.youtube.com/watch?v=N65Gp60ix_o', '2024-04-01 22:00:00', './music/Buddy Holly - Neco Arc [A.I. Cover]-La-Creatura.opus', 0, 164),
(422, 'Neco Arc - Es Épico (AI Cover)', 'Frambueso', 'https://www.youtube.com/@frambuesogod', 'https://www.youtube.com/watch?v=ry7mnXHtvtg', '2024-04-01 22:00:00', './music/Neco Arc - Es Épico (AI Cover)-Frambueso.opus', 0, 362),
(423, 'Neco Arc AI cover - Golden Hour', 'Agalo', 'https://www.youtube.com/@agalo724', 'https://www.youtube.com/watch?v=HwqlApVtGXQ', '2024-04-01 22:00:00', './music/Neco Arc AI cover - Golden Hour-Agalo.opus', 0, 210),
(424, 'Break My Stride - Neco Arc [A.I. Cover]', 'La-Creatura', 'https://www.youtube.com/@La-Creatura', 'https://www.youtube.com/watch?v=Vux0p57LTZc', '2024-04-01 22:00:00', './music/Break My Stride - Neco Arc [A.I. Cover]-La-Creatura.opus', 0, 186),
(425, 'Neco Arc sings Komm Süsser Tod - Come Sweet Death (AI COVER)', 'Hanii', 'https://www.youtube.com/@Haniety', 'https://www.youtube.com/watch?v=LlznZVyxjjM', '2024-04-01 22:00:00', './music/Neco Arc sings Komm Süsser Tod - Come Sweet Death (AI COVER)-Hanii.opus', 0, 461),
(426, 'Neco arc sings Deutschland (AI cover)', 'Neco Chaos', 'https://www.youtube.com/@NecoChaos_fan', 'https://www.youtube.com/watch?v=y6FLCx9oFQw', '2024-04-01 22:00:00', './music/Neco arc sings Deutschland (AI cover)-Neco Chaos.opus', 0, 322),
(427, 'Neco arc sings Coco Jamboo (Ai cover)', 'Neco Chaos', 'https://www.youtube.com/@NecoChaos_fan', 'https://www.youtube.com/watch?v=muyPCAUKsdE', '2024-04-01 22:00:00', './music/Neco arc sings Coco Jamboo (Ai cover)-Neco Chaos.opus', 0, 219),
(428, 'Neco-Arc – Mr. Brightside (The Killers AI Cover)', 'NECO', 'https://www.youtube.com/@NECO2926', 'https://www.youtube.com/watch?v=-5lzIZ0b2F8', '2024-04-01 22:00:00', './music/Neco-Arc – Mr. Brightside (The Killers AI Cover)-NECO.opus', 0, 222),
(429, 'Nickelback - How You Remind Me | Neco Arc (AI Cover)', 'Jolitrub', 'https://www.youtube.com/@jolitrub', 'https://www.youtube.com/watch?v=txCeZau21Y4', '2024-04-01 22:00:00', './music/Nickelback - How You Remind Me | Neco Arc (AI Cover)-Jolitrub.opus', 0, 224),
(430, 'Neco Arc - I Touch Myself (The Divinyls) AI Cover', 'ScorchedCube', 'https://www.youtube.com/@ScorchedCube', 'https://www.youtube.com/watch?v=InHB5RSPank', '2024-04-01 22:00:00', './music/Neco Arc - I Touch Myself (The Divinyls) AI Cover-ScorchedCube.opus', 0, 228),
(431, 'Neco Arc - Absolute Territory [ AI Cover ]', 'christang', 'https://www.youtube.com/@christangTheOne', 'https://www.youtube.com/watch?v=-FiJ4iA62Hw', '2024-04-01 22:00:00', './music/Neco Arc - Absolute Territory [ AI Cover ]-christang.opus', 0, 269),
(432, 'Neco Arc - Shiroyama (AI Cover)', 'Bewsewk', 'https://www.youtube.com/@Leels', 'https://www.youtube.com/watch?v=q853z-FOHGY', '2024-04-01 22:00:00', './music/Neco Arc - Shiroyama (AI Cover)-Bewsewk.opus', 0, 210),
(433, 'Neco Arc - Space Song [ AI Cover ]', 'christang', 'https://www.youtube.com/@christangTheOne', 'https://www.youtube.com/watch?v=0aKO3RMf_HM', '2024-04-01 22:00:00', './music/Neco Arc - Space Song [ AI Cover ]-christang.opus', 0, 321),
(434, 'Neco arc sings Ghostbusters (Ai cover)', 'Neco Chaos', 'https://www.youtube.com/@NecoChaos_fan', 'https://www.youtube.com/watch?v=oqKEbcXiBbc', '2024-04-01 22:00:00', './music/Neco arc sings Ghostbusters (Ai cover)-Neco Chaos.opus', 0, 245),
(435, 'Neco arc sings Wolf In Sheeps Clothing  (Ai cover)', 'Neco Chaos', 'https://www.youtube.com/@NecoChaos_fan', 'https://www.youtube.com/watch?v=_Q2iABlIopg', '2024-04-01 22:00:00', './music/Neco arc sings Wolf In Sheeps Clothing  (Ai cover)-Neco Chaos.opus', 0, 187),
(436, 'Neco arc sings I need dollar (Ai cover)', 'Neco Chaos', 'https://www.youtube.com/@NecoChaos_fan', 'https://www.youtube.com/watch?v=1d1x3qnnaQY', '2024-04-01 22:00:00', './music/Neco arc sings I need dollar (Ai cover)-Neco Chaos.opus', 0, 243),
(438, 'Neco-Arc sings Take On Me', 'l1minal', 'https://www.youtube.com/@l1minal541', 'https://www.youtube.com/watch?v=F2WCEbp765I', '2024-04-01 22:00:00', './music/Neco-Arc sings Take On Me-l1minal.opus', 0, 227),
(439, 'Welcome to the Black Purrade - Neco Arc AI MCR Cover', 'SinewaveDotZone', 'https://www.youtube.com/@SinewaveDotZone', 'https://www.youtube.com/watch?v=Ok9A99pJxzs', '2024-04-01 22:00:00', './music/Welcome to the Black Purrade - Neco Arc AI MCR Cover-SinewaveDotZone.opus', 0, 301),
(440, 'neco arc cover  -  Dani California', 'blorg lounge', 'https://www.youtube.com/@blorglounge6158', 'https://www.youtube.com/watch?v=nEuQk3Wmkrc', '2024-04-01 22:00:00', './music/neco arc cover  -  Dani California-blorg lounge.opus', 0, 285),
(441, 'Neco Arc - Miss Murder (Ai Cover)', 'GamerGunk22', 'https://www.youtube.com/@GamerGunk22', 'https://www.youtube.com/watch?v=GvBfYsZ9Quc', '2024-04-01 22:00:00', './music/Neco Arc - Miss Murder (Ai Cover)-GamerGunk22.opus', 0, 207),
(442, 'Johnny B Goode - Neco Arc [AI Cover]', '5MO', 'https://www.youtube.com/@5MO', 'https://www.youtube.com/watch?v=anGx8tW0RPk', '2024-04-01 22:00:00', './music/Johnny B Goode - Neco Arc [AI Cover]-5MO.opus', 0, 163),
(445, 'Neco Arc Heartaches By The Number', 'Benelope Almendra', 'https://www.youtube.com/@BenelopeAlmendra', 'https://www.youtube.com/watch?v=C5Z7sZZ06Bs', '2024-04-01 22:00:00', './music/Neco Arc Heartaches By The Number-Benelope Almendra.opus', 0, 160),
(446, 'Neco arc sings Seven Nation Army (Ai cover)', 'Neco Chaos', 'https://www.youtube.com/@NecoChaos_fan', 'https://www.youtube.com/watch?v=w4d7mN2I66I', '2024-04-01 22:00:00', './music/Neco arc sings Seven Nation Army (Ai cover)-Neco Chaos.opus', 0, 231),
(447, 'Eiffel 65 - Blue [Neco Arc AI COVER]', 'Moni', 'https://www.youtube.com/@fowi6761', 'https://www.youtube.com/watch?v=8VT5mTNzlDE', '2024-04-01 22:00:00', './music/Eiffel 65 - Blue [Neco Arc AI COVER]-Moni.opus', 0, 286),
(448, 'Neco Arc - Raindrops keep falling on my head [ AI Cover ]', 'Un random', 'https://www.youtube.com/@unRandom__', 'https://www.youtube.com/watch?v=kq4_z5BQuFY', '2024-04-01 22:00:00', './music/Neco Arc - Raindrops keep falling on my head [ AI Cover ]-Un random.opus', 0, 178),
(449, 'Foo Fighters - Everlong (Neco Arc AI Cover)', 'ltpck', 'https://www.youtube.com/@ltpck', 'https://www.youtube.com/watch?v=nh2OYK_faao', '2024-04-01 22:00:00', './music/Foo Fighters - Everlong (Neco Arc AI Cover)-ltpck.opus', 0, 251),
(450, 'Radiohead - Just (Neco Arc AI Cover)', 'ltpck', 'https://www.youtube.com/@ltpck', 'https://www.youtube.com/watch?v=lqch5mHzFvU', '2024-04-01 22:00:00', './music/Radiohead - Just (Neco Arc AI Cover)-ltpck.opus', 0, 209),
(451, 'Neco Spice Girls - Wannabe (AI Cover)', 'ltpck', 'https://www.youtube.com/@ltpck', 'https://www.youtube.com/watch?v=taXOzs9OW00', '2024-04-01 22:00:00', './music/Neco Spice Girls - Wannabe (AI Cover)-ltpck.opus', 0, 171),
(452, 'Neco Arc Gosling - Push (AI Cover)', 'ltpck', 'https://www.youtube.com/@ltpck', 'https://www.youtube.com/watch?v=bBKB2WLhwKg', '2024-04-01 22:00:00', './music/Neco Arc Gosling - Push (AI Cover)-ltpck.opus', 0, 201),
(453, 'Neco Arc - Все идет по плану (AI COVER)', 'Дима Mojong', 'https://www.youtube.com/@TheMojongChannel', 'https://www.youtube.com/watch?v=ae-A7whTznc', '2024-04-01 22:00:00', './music/Neco Arc - Все идет по плану (AI COVER)-Дима Mojong.opus', 0, 182),
(454, 'Neco arc — Русская дорога (AI Cover)', 'Олежа Паштет', 'https://www.youtube.com/@user-wx2ni7xo3k', 'https://www.youtube.com/watch?v=XNhhKvpeLoE', '2024-04-01 22:00:00', './music/Neco arc — Русская дорога (AI Cover)-Олежа Паштет.opus', 0, 180),
(455, 'Peter Griffin and Neco Arc Sing Somebody That I Used To Know', 'imfrybro', 'https://www.youtube.com/@imfrybro', 'https://www.youtube.com/watch?v=98KEUsuyDuU', '2024-04-01 22:00:00', './music/Peter Griffin and Neco Arc Sing Somebody That I Used To Know-imfrybro.opus', 0, 246),
(456, 'Peter Griffin and Neco Arc Sing the Minecraft Creeper Rap', 'imfrybro', 'https://www.youtube.com/@imfrybro', 'https://www.youtube.com/watch?v=0bLp_WX5fHM', '2024-04-01 22:00:00', './music/Peter Griffin and Neco Arc Sing the Minecraft Creeper Rap-imfrybro.opus', 0, 144),
(457, 'Peter Griffin and Neco Arc Sing Feel It Still', 'imfrybro', 'https://www.youtube.com/@imfrybro', 'https://www.youtube.com/watch?v=XEEnwGqr-tQ', '2024-04-01 22:00:00', './music/Peter Griffin and Neco Arc Sing Feel It Still-imfrybro.opus', 0, 164),
(458, 'Neco Arc - Toxic【AI Cover】', 'Tanger', 'https://www.youtube.com/@Tangermusic', 'https://www.youtube.com/watch?v=laoXokvIBME', '2024-04-01 22:00:00', './music/Neco Arc - Toxic【AI Cover】-Tanger.opus', 0, 200),
(459, 'Neco Arc - Violent Pornography', 'Xylos den', 'https://www.youtube.com/@Xylosden', 'https://www.youtube.com/watch?v=yAPL4Pg6cPQ', '2024-04-01 22:00:00', './music/Neco Arc - Violent Pornography-Xylos den.opus', 0, 213),
(460, 'Neco Arc - I Will Survive (AI Cover)', 'KorboTheWise', 'https://www.youtube.com/@KorboTheWise', 'https://www.youtube.com/watch?v=lzjc7dflho0', '2024-04-01 22:00:00', './music/Neco Arc - I Will Survive (AI Cover)-KorboTheWise.opus', 0, 194),
(461, 'Neco Arc - These Boots Are Made For Walkin (AI Cover)', 'KorboTheWise', 'https://www.youtube.com/@KorboTheWise', 'https://www.youtube.com/watch?v=9sK72lKhOJA', '2024-04-01 22:00:00', './music/Neco Arc - These Boots Are Made For Walkin (AI Cover)-KorboTheWise.opus', 0, 168),
(462, 'Neco Arc - No Suprises(Ai Cover)', 'GamerGunk22', 'https://www.youtube.com/@GamerGunk22', 'https://www.youtube.com/watch?v=do-CAwDznB0', '2024-04-01 22:00:00', './music/Neco Arc - No Suprises(Ai Cover)-GamerGunk22.opus', 0, 229),
(463, 'Neco Arc - Hayloft (Ai Cover)', 'GamerGunk22', 'https://www.youtube.com/@GamerGunk22', 'https://www.youtube.com/watch?v=jHCs9VLKiUw', '2024-04-01 22:00:00', './music/Neco Arc - Hayloft (Ai Cover)-GamerGunk22.opus', 0, 182),
(464, 'Neco-Arc  - Stairway to Heaven (Led Zeppelin AI Cover)', 'Chlorine', 'https://www.youtube.com/@mChlorine', 'https://www.youtube.com/watch?v=L8_EVrpQoBA', '2024-04-01 22:00:00', './music/Neco-Arc  - Stairway to Heaven (Led Zeppelin AI Cover)-Chlorine.opus', 0, 483),
(465, 'Neco Arc - Dont Stop Me Now | Neco Arc AI Cover (REUPLOAD)', 'Sleestiq Music', 'https://www.youtube.com/@SleestiqMusic', 'https://www.youtube.com/watch?v=VLGceP5MwsQ', '2024-04-01 22:00:00', './music/Neco Arc - Dont Stop Me Now | Neco Arc AI Cover (REUPLOAD)-Sleestiq Music.opus', 0, 216),
(466, 'Neco Arc - Cotton Eye Joe (AI Cover)', 'rsdelta', 'https://www.youtube.com/@rsdelta', 'https://www.youtube.com/watch?v=f3uAHVj-WlQ', '2024-04-01 22:00:00', './music/Neco Arc - Cotton Eye Joe (AI Cover)-rsdelta.opus', 0, 192),
(467, 'Neco Arc - Voyage Voyage (AI Cover)', 'rsdelta', 'https://www.youtube.com/@rsdelta', 'https://www.youtube.com/watch?v=mGCxGcGVKpI', '2024-04-01 22:00:00', './music/Neco Arc - Voyage Voyage (AI Cover)-rsdelta.opus', 0, 258),
(468, 'Neco Arc And The Andrews Sisters - Civilization (Bingo Bango Bongo) [Fallout 3 AI Cover]', 'Honchu', 'https://www.youtube.com/@Honchu1', 'https://www.youtube.com/watch?v=TuRauciXt2k', '2024-04-01 22:00:00', './music/Neco Arc And The Andrews Sisters - Civilization (Bingo Bango Bongo) [Fallout 3 AI Cover]-Honchu.opus', 0, 181),
(469, 'neco arc - creep ai cover', 'nxclip', 'https://www.youtube.com/@nxclipcs', 'https://www.youtube.com/watch?v=ZLPUDaAQjiU', '2024-04-01 22:00:00', './music/neco arc - creep ai cover-nxclip.opus', 0, 241),
(470, 'Neco Arc & Knuckles - Unknown from M.E. (Sonic Adventure Knuckles Theme AI Cover)', 'Honchu', 'https://www.youtube.com/@Honchu1', 'https://www.youtube.com/watch?v=ReXFBvqgc_E', '2024-04-01 22:00:00', './music/Neco Arc & Knuckles - Unknown from M.E. (Sonic Adventure Knuckles Theme AI Cover)-Honchu.opus', 0, 266),
(471, 'Areosmith Dream on Neco Arc (AI Cover)', 'Lucoa-San', 'https://www.youtube.com/@lucoa-gaming8621', 'https://www.youtube.com/watch?v=rgqlOijH-1E', '2024-04-01 22:00:00', './music/Areosmith Dream on Neco Arc (AI Cover)-Lucoa-San.opus', 0, 268),
(472, 'Pink Guy - セックス大好き (I Love Sex) [Neco Arc AI Cover]', 'FloppedFR', 'https://www.youtube.com/@floppedforrealsies', 'https://www.youtube.com/watch?v=6dhAvHi48n4', '2024-04-01 22:00:00', './music/Pink Guy - セックス大好き (I Love Sex) [Neco Arc AI Cover]-FloppedFR.opus', 0, 143),
(473, 'Neco Arc - What is love', 'golub inside', 'https://www.youtube.com/@golub_inside', 'https://www.youtube.com/watch?v=_HLOxSLc4kU', '2024-04-01 22:00:00', './music/Neco Arc - What is love-golub inside.opus', 0, 278),
(474, 'Neco Arc - Viva la Vida (Coldplay Cover)', 'Kip', 'https://www.youtube.com/@Kippuin', 'https://www.youtube.com/watch?v=qgEYQkTXdsI', '2024-04-01 22:00:00', './music/Neco Arc - Viva la Vida (Coldplay Cover)-Kip.opus', 0, 242),
(475, 'neco arc dilemma (meow) but she sing it', 'christang', 'https://www.youtube.com/@christangTheOne', 'https://www.youtube.com/watch?v=iGiKqRikSJ8', '2024-04-01 22:00:00', './music/neco arc dilemma (meow) but she sing it-christang.opus', 0, 251),
(476, 'as the world caves in (neco arc AI cover)', 'hat in hell', 'https://www.youtube.com/@hatinhell', 'https://www.youtube.com/watch?v=JlgULUUz8gE', '2024-04-01 22:00:00', './music/as the world caves in (neco arc AI cover)-hat in hell.opus', 0, 221),
(477, 'De Música Ligera - Neco arc AI Cover', 'Yuka en Tanga', 'https://www.youtube.com/@Yuka_Tanga', 'https://www.youtube.com/watch?v=ZAKdB42KmlA', '2024-04-01 22:00:00', './music/De Música Ligera - Neco arc AI Cover-Yuka en Tanga.opus', 0, 214),
(479, 'Neco Arc - Two Truck [ AI Cover ]', 'christang', 'https://www.youtube.com/@christangTheOne', 'https://www.youtube.com/watch?v=E28ryC5dEYE', '2024-04-01 22:00:00', './music/Neco Arc - Two Truck [ AI Cover ]-christang.opus', 0, 251),
(480, 'Neco-Arc Sings - Smell of the Game | Guilty Gear (A.I Cover)', 'BettersonMcgee', 'https://www.youtube.com/@BettersonMcgee', 'https://www.youtube.com/watch?v=j4BgmhRIc-c', '2024-04-01 22:00:00', './music/Neco-Arc Sings - Smell of the Game | Guilty Gear (A.I Cover)-BettersonMcgee.opus', 0, 304),
(481, 'DMC 5 - Bury The Light | Neco Arc AI cover', 'Trole', 'https://www.youtube.com/@Trole.', 'https://www.youtube.com/watch?v=CfP3T834x_A', '2024-04-01 22:00:00', './music/DMC 5 - Bury The Light | Neco Arc AI cover-Trole.opus', 0, 583),
(482, 'Neco Arc Sings Chicken Fried', 'Cigarette', 'https://www.youtube.com/@OrigionalCigarette', 'https://www.youtube.com/watch?v=njneF2y6TJ4', '2024-04-01 22:00:00', './music/Neco Arc Sings Chicken Fried-Cigarette.opus', 0, 210),
(483, 'Still Alive Neco Arc (AI cover)', 'La-Creatura', 'https://www.youtube.com/@La-Creatura', 'https://www.youtube.com/watch?v=V0S7ahjaPf4', '2024-04-01 22:00:00', './music/Still Alive Neco Arc (AI cover)-La-Creatura.opus', 0, 198),
(484, 'Neco Arc, Hatsune Miku - Нас Не Догонят (AI Cover)', 'FliKer', 'https://www.youtube.com/@fl1ktm', 'https://www.youtube.com/watch?v=txEs2U20nro', '2024-04-01 22:00:00', './music/Neco Arc, Hatsune Miku - Нас Не Догонят (AI Cover)-FliKer.opus', 0, 277),
(485, 'Neco-Arc got the moves like jagger', 'l1minal', 'https://www.youtube.com/@l1minal541', 'https://www.youtube.com/watch?v=dRo7V_a3kKQ', '2024-04-01 22:00:00', './music/Neco-Arc got the moves like jagger-l1minal.opus', 0, 208),
(486, 'Neco Arc - Scarface (Push It To The Limit) (Ai Cover)', 'Ai Neco Arc', 'https://www.youtube.com/@AiNecoArc', 'https://www.youtube.com/watch?v=UcWPDO2JCSE', '2024-04-01 22:00:00', './music/Neco Arc - Scarface (Push It To The Limit) (Ai Cover)-Ai Neco Arc.opus', 0, 179),
(487, 'Deja vu - Neco arc (Ai cover)', 'Neco Chaos', 'https://www.youtube.com/@NecoChaos_fan', 'https://www.youtube.com/watch?v=XZmLWhg1ACA', '2024-04-01 22:00:00', './music/Deja vu - Neco arc (Ai cover)-Neco Chaos.opus', 0, 264),
(488, 'Neco Arc - Red Hot Chili Peppers - Cant Stop (AI Cover)', 'rsdelta', 'https://www.youtube.com/@rsdelta', 'https://www.youtube.com/watch?v=8X47cnHwG3g', '2024-04-01 22:00:00', './music/Neco Arc - Red Hot Chili Peppers - Cant Stop (AI Cover)-rsdelta.opus', 0, 271),
(490, 'Neco Arc - Big Iron', 'MrARTBUT', 'https://www.youtube.com/@MrARTBUT', 'https://www.youtube.com/watch?v=8zgwMx_TD68', '2024-04-01 22:00:00', './music/Neco Arc - Big Iron-MrARTBUT.opus', 0, 240),
(491, 'Neco Arc - Artiljerija |AI COVER|', 'UnDrannik', 'https://www.youtube.com/@undrannik', 'https://www.youtube.com/watch?v=siOGwAkZ718', '2024-04-01 22:00:00', './music/Neco Arc - Artiljerija |AI COVER|-UnDrannik.opus', 0, 216),
(492, 'Neco Arc - Take Me to Church (Hozier Cover)', 'Kip', 'https://www.youtube.com/@Kippuin', 'https://www.youtube.com/watch?v=neyi4zg6tRA', '2024-04-01 22:00:00', './music/Neco Arc - Take Me to Church (Hozier Cover)-Kip.opus', 0, 242),
(493, 'Ice Cube - It Was A Good Day ( Neco-Arc AI Cover)', 'vaev', 'https://www.youtube.com/@vaevv', 'https://www.youtube.com/watch?v=agL2NFCXMCE', '2024-04-01 22:00:00', './music/Ice Cube - It Was A Good Day ( Neco-Arc AI Cover)-vaev.opus', 0, 266),
(494, 'Neco arc sings Hava Nagila | ai cover', 'Tailsaro', 'https://www.youtube.com/@tailsaro', 'https://www.youtube.com/watch?v=GtEY6_aE-us', '2024-04-01 22:00:00', './music/Neco arc sings Hava Nagila | ai cover-Tailsaro.opus', 0, 181),
(495, 'Neco Arc - Look at the owl [AI Cover]', 'Добряк Хома', 'https://www.youtube.com/@dobryakhoma', 'https://www.youtube.com/watch?v=EmpPGwELXEs', '2024-04-01 22:00:00', './music/Neco Arc - Look at the owl [AI Cover]-Добряк Хома.opus', 0, 94),
(497, 'Time in a Bottle -Jim Croce [AI Cover]', 'neco arc', 'https://www.youtube.com/@byurenyu', 'https://www.youtube.com/watch?v=vSeCRag268k', '2024-04-01 22:00:00', './music/Time in a Bottle -Jim Croce [AI Cover]-neco arc.opus', 0, 141),
(498, 'Necromancin Dancin - Bear Ghost [AI-Cover]', 'neco arc', 'https://www.youtube.com/@byurenyu', 'https://www.youtube.com/watch?v=_cCO0lWcJCk', '2024-04-01 22:00:00', './music/Necromancin Dancin - Bear Ghost [AI-Cover]-neco arc.opus', 0, 208),
(499, 'Santeria - Sublime [AI Cover]', 'neco arc', 'https://www.youtube.com/@byurenyu', 'https://www.youtube.com/watch?v=C3Aw5o9jQYw', '2024-04-01 22:00:00', './music/Santeria - Sublime [AI Cover]-neco arc.opus', 0, 184),
(500, 'Neco Arc - Ну что ж ты страшная такая (AI Cover)', 'rsdelta', 'https://www.youtube.com/@rsdelta', 'https://www.youtube.com/watch?v=MC2aikei3Bc', '2024-04-01 22:00:00', './music/Neco Arc - Ну что ж ты страшная такая (AI Cover)-rsdelta.opus', 0, 212),
(501, 'Neco Arc - У шамана три руки (AI Cover)', 'rsdelta', 'https://www.youtube.com/@rsdelta', 'https://www.youtube.com/watch?v=fHEOuOpYFfM', '2024-04-01 22:00:00', './music/Neco Arc - У шамана три руки (AI Cover)-rsdelta.opus', 0, 203),
(502, 'Neco Arc Chaos - Runaway Train (AI Cover)', 'rsdelta', 'https://www.youtube.com/@rsdelta', 'https://www.youtube.com/watch?v=LTpE8RkXFHg', '2024-04-01 22:00:00', './music/Neco Arc Chaos - Runaway Train (AI Cover)-rsdelta.opus', 0, 254),
(503, 'Neco Arc - Red Hot Chili Peppers - By The Way (AI Cover)', 'rsdelta', 'https://www.youtube.com/@rsdelta', 'https://www.youtube.com/watch?v=QdaCpDKHFzk', '2024-04-01 22:00:00', './music/Neco Arc - Red Hot Chili Peppers - By The Way (AI Cover)-rsdelta.opus', 0, 216),
(504, 'Neco Arc - David Bowie - Lets Dance (AI Cover)', 'rsdelta', 'https://www.youtube.com/@rsdelta', 'https://www.youtube.com/watch?v=JJJDtJuZlZM', '2024-04-01 22:00:00', './music/Neco Arc - David Bowie - Lets Dance (AI Cover)-rsdelta.opus', 0, 240),
(505, 'Neco Arc - Alphaville - Big in Japan (AI Cover)', 'rsdelta', 'https://www.youtube.com/@rsdelta', 'https://www.youtube.com/watch?v=T2nltVtzS0c', '2024-04-01 22:00:00', './music/Neco Arc - Alphaville - Big in Japan (AI Cover)-rsdelta.opus', 0, 222),
(506, 'Neco Arc - Black Hole Sun (Soundgarden Cover)', 'Kip', 'https://www.youtube.com/@Kippuin', 'https://www.youtube.com/watch?v=lhlycSPu1V8', '2024-04-01 22:00:00', './music/Neco Arc - Black Hole Sun (Soundgarden Cover)-Kip.opus', 0, 320),
(507, 'Neco Arc - Rhythm Is A Dancer (Ai Cover)', 'FliKer', 'https://www.youtube.com/@fl1ktm', 'https://www.youtube.com/watch?v=SKI1TU4scCw', '2024-04-01 22:00:00', './music/Neco Arc - Rhythm Is A Dancer (Ai Cover)-FliKer.opus', 0, 221),
(508, 'Neco Arc - oddloop (Neco Arc AI Cover)', 'FliKer', 'https://www.youtube.com/@fl1ktm', 'https://www.youtube.com/watch?v=P7idle_HF48', '2024-04-01 22:00:00', './music/Neco Arc - oddloop (Neco Arc AI Cover)-FliKer.opus', 0, 262),
(509, 'Neco Arc - CHA CHA CHA (AI cover)', 'omnivirtu', 'https://www.youtube.com/@omnivirtu', 'https://www.youtube.com/watch?v=98X4Ye4-SSI', '2024-04-01 22:00:00', './music/Neco Arc - CHA CHA CHA (AI cover)-omnivirtu.opus', 0, 176),
(511, 'Neco Arc śpiewa intro Świat Według Kiepskich (AI Cover)', 'rwqsak', 'https://www.youtube.com/@rwqsak', 'https://www.youtube.com/watch?v=T0OBlqGJQ8g', '2024-04-01 22:00:00', './music/Neco Arc śpiewa intro Świat Według Kiepskich (AI Cover)-rwqsak.opus', 0, 102),
(513, 'Neco arc - Po twojej pysznej zupie (AI Cover)', 'Yuvera', 'https://www.youtube.com/@Yuvera', 'https://www.youtube.com/watch?v=9iEwqH3md4A', '2024-04-01 22:00:00', './music/Neco arc - Po twojej pysznej zupie (AI Cover)-Yuvera.opus', 0, 109),
(514, 'Neco Arc Cover Enej - Tak Smakuje Życie (AI Cover)', 'Adamms', 'https://www.youtube.com/@Adamms18', 'https://www.youtube.com/watch?v=ilFIMieml7U', '2024-04-01 22:00:00', './music/Neco Arc Cover Enej - Tak Smakuje Życie (AI Cover)-Adamms.opus', 0, 220),
(515, 'Neco Arc cover Enej - Jeśli chcesz (AI Cover)', 'Adamms', 'https://www.youtube.com/@Adamms18', 'https://www.youtube.com/watch?v=oqPLTQWHgQk', '2024-04-01 22:00:00', './music/Neco Arc cover Enej - Jeśli chcesz (AI Cover)-Adamms.opus', 0, 204),
(516, 'Bring Me The Horizon - Can You Feel My Heart neco arc AI cover', 'Trole', 'https://www.youtube.com/@Trole.', 'https://www.youtube.com/watch?v=9G5OuXB3Rfk', '2024-04-01 22:00:00', './music/Bring Me The Horizon - Can You Feel My Heart neco arc AI cover-Trole.opus', 0, 227),
(517, 'Neco Arc - Come as You Are [AI Cover]', 'Nesqquick2', 'https://www.youtube.com/@Nesqquick2', 'https://www.youtube.com/watch?v=BCeQBKkS9bg', '2024-04-01 22:00:00', './music/Neco Arc - Come as You Are [AI Cover]-Nesqquick2.opus', 0, 219),
(518, 'Neco Arc - NEVEREVER [AI Cover]', 'Nesqquick2', 'https://www.youtube.com/@Nesqquick2', 'https://www.youtube.com/watch?v=myQ-SIQyeXA', '2024-04-01 22:00:00', './music/Neco Arc - NEVEREVER [AI Cover]-Nesqquick2.opus', 0, 144),
(519, 'Neco Arc - Moulaga  [AI Cover] speed up', 'Nesqquick2', 'https://www.youtube.com/@Nesqquick2', 'https://www.youtube.com/watch?v=p4ZYVHavtKg', '2024-04-01 22:00:00', './music/Neco Arc - Moulaga  [AI Cover] speed up-Nesqquick2.opus', 0, 164),
(520, 'Neco Arc - В военкомате случай был [AI Cover]', 'Nesqquick2', 'https://www.youtube.com/@Nesqquick2', 'https://www.youtube.com/watch?v=Ja9asd6c7nA', '2024-04-01 22:00:00', './music/Neco Arc - В военкомате случай был [AI Cover]-Nesqquick2.opus', 0, 186),
(521, 'Neco Arc - Ultimate [AI Cover] (специально для 1к)', 'Nesqquick2', 'https://www.youtube.com/@Nesqquick2', 'https://www.youtube.com/watch?v=R4LGlnoxgJA', '2024-04-01 22:00:00', './music/Neco Arc - Ultimate [AI Cover] (специально для 1к)-Nesqquick2.opus', 0, 190),
(522, 'Neco Arc - 7 Этаж [AI Cover]', 'Nesqquick2', 'https://www.youtube.com/@Nesqquick2', 'https://www.youtube.com/watch?v=6wfuGxNKhb4', '2024-04-01 22:00:00', './music/Neco Arc - 7 Этаж [AI Cover]-Nesqquick2.opus', 0, 186),
(523, 'Neco Arc - Пора Домой [AI Cover]', 'Nesqquick2', 'https://www.youtube.com/@Nesqquick2', 'https://www.youtube.com/watch?v=JVJWPpLxOKU', '2024-04-01 22:00:00', './music/Neco Arc - Пора Домой [AI Cover]-Nesqquick2.opus', 0, 236),
(524, 'Neco Arc - Runaway [AI Cover]', 'Nesqquick2', 'https://www.youtube.com/@Nesqquick2', 'https://www.youtube.com/watch?v=69P65tP0OZA', '2024-04-01 22:00:00', './music/Neco Arc - Runaway [AI Cover]-Nesqquick2.opus', 0, 184),
(525, 'Neco Arc Chaos - Спортивные очки [AI Cover]', 'Nesqquick2', 'https://www.youtube.com/@Nesqquick2', 'https://www.youtube.com/watch?v=FgEB-HUW8jY', '2024-04-01 22:00:00', './music/Neco Arc Chaos - Спортивные очки [AI Cover]-Nesqquick2.opus', 0, 135),
(526, 'Neco Arc - Лихолесье (AI COVER)', 'Дима Mojong', 'https://www.youtube.com/@TheMojongChannel', 'https://www.youtube.com/watch?v=nMmYh2M9T2A', '2024-04-01 22:00:00', './music/Neco Arc - Лихолесье (AI COVER)-Дима Mojong.opus', 0, 260),
(527, 'Нэко Арк - ШУЕ (AI Cover)', 'edshirnyj', 'https://www.youtube.com/@edshir228', 'https://www.youtube.com/watch?v=GoxJv3rFCFI', '2024-04-01 22:00:00', './music/Нэко Арк - ШУЕ (AI Cover)-edshirnyj.opus', 0, 141),
(528, 'Neco Arc - Sawed Off Shotgun (AI Cover)', 'edshirnyj', 'https://www.youtube.com/@edshir228', 'https://www.youtube.com/watch?v=7fXLl4F23mc', '2024-04-01 22:00:00', './music/Neco Arc - Sawed Off Shotgun (AI Cover)-edshirnyj.opus', 0, 197),
(529, 'Нэко Арк - Смерть неизбежна (AI Cover)', 'edshirnyj', 'https://www.youtube.com/@edshir228', 'https://www.youtube.com/watch?v=FUIthOQEh5o', '2024-04-01 22:00:00', './music/Нэко Арк - Смерть неизбежна (AI Cover)-edshirnyj.opus', 0, 181),
(530, 'Трофим - Мурка (Neco Arc) [AI Cover]', 'Gaz.mp4', 'https://www.youtube.com/@gaz.mp4', 'https://www.youtube.com/watch?v=xLL6iR_E0os', '2024-04-01 22:00:00', './music/Трофим - Мурка (Neco Arc) [AI Cover]-Gaz.mp4.opus', 0, 212),
(531, 'Bomfunk MCs - Freestyler  (Neco arc Ai cover)', 'H.D.P.L.', 'https://www.youtube.com/@H.D.P.L.', 'https://www.youtube.com/watch?v=3az6VOH15cE', '2024-04-01 22:00:00', './music/Bomfunk MCs - Freestyler  (Neco arc Ai cover)-H.D.P.L..opus', 0, 294),
(532, 'ChuChu Lovely - Neco Arc (AI Cover)', 'sisu', 'https://www.youtube.com/@suomalaiset', 'https://www.youtube.com/watch?v=gcsu2Qd4P3s', '2024-04-01 22:00:00', './music/ChuChu Lovely - Neco Arc (AI Cover)-sisu.opus', 0, 186),
(533, 'Deep Purple - Highway Star  (Neco arc Ai cover)', 'H.D.P.L.', 'https://www.youtube.com/@H.D.P.L.', 'https://www.youtube.com/watch?v=7_rjRbemU3I', '2024-04-01 22:00:00', './music/Deep Purple - Highway Star  (Neco arc Ai cover)-H.D.P.L..opus', 0, 368),
(534, 'Welcome To The Jungle - Neco arc (Ai cover)', 'Neco Chaos', 'https://www.youtube.com/@NecoChaos_fan', 'https://www.youtube.com/watch?v=vr0rI7Peu2I', '2024-04-01 22:00:00', './music/Welcome To The Jungle - Neco arc (Ai cover)-Neco Chaos.opus', 0, 274),
(535, 'Ievan Polkka · Korpiklaani  (Neco arc Ai cover)', 'H.D.P.L.', 'https://www.youtube.com/@H.D.P.L.', 'https://www.youtube.com/watch?v=rGw_n5_x8vk', '2024-04-01 22:00:00', './music/Ievan Polkka · Korpiklaani  (Neco arc Ai cover)-H.D.P.L..opus', 0, 188),
(536, 'Im Still Standing - Neco arc [ai cover]', 'Mortadelita0w0', 'https://www.youtube.com/@mortadelita0w042', 'https://www.youtube.com/watch?v=o5PzQlU1ZaI', '2024-04-01 22:00:00', './music/Im Still Standing - Neco arc [ai cover]-Mortadelita0w0.opus', 0, 185),
(537, 'Just the Two of Us - neco-arc ai cover but with memes and lyrics', 'nzcsx', 'https://www.youtube.com/@nzcsx', 'https://www.youtube.com/watch?v=YfwvpIyCKYk', '2024-04-01 22:00:00', './music/Just the Two of Us - neco-arc ai cover but with memes and lyrics-nzcsx.opus', 0, 202),
(538, 'Linkin Park - Given Up (Neco Arc A.I Cover)', 'LeeWolf', 'https://www.youtube.com/@LeeW0lf', 'https://www.youtube.com/watch?v=iVxz1nPsYbQ', '2024-04-01 22:00:00', './music/Linkin Park - Given Up (Neco Arc A.I Cover)-LeeWolf.opus', 0, 190);
INSERT INTO `music` (`id`, `title`, `producer`, `producer_url`, `source_url`, `last_played`, `music_path`, `playing`, `length`) VALUES
(539, 'Neco Arc - Europe - The Final Countdown (AI Cover)', 'rsdelta', 'https://www.youtube.com/@rsdelta', 'https://www.youtube.com/watch?v=BJjPMVSLt68', '2024-04-01 22:00:00', './music/Neco Arc - Europe - The Final Countdown (AI Cover)-rsdelta.opus', 0, 305),
(540, 'Neco Arc - Guano Apes - Lords Of The Boards (AI Cover)', 'rsdelta', 'https://www.youtube.com/@rsdelta', 'https://www.youtube.com/watch?v=h--f5-5oKQc', '2024-04-01 22:00:00', './music/Neco Arc - Guano Apes - Lords Of The Boards (AI Cover)-rsdelta.opus', 0, 218),
(541, 'Neco Arc - Hallelujah (AI Cover)', 'figas', 'https://www.youtube.com/@figas126', 'https://www.youtube.com/watch?v=7VDyULfWEoM', '2024-04-01 22:00:00', './music/Neco Arc - Hallelujah (AI Cover)-figas.opus', 0, 417),
(542, 'Neco Arc - Hand Of Blood (AI Cover)', 'FliKer', 'https://www.youtube.com/@fl1ktm', 'https://www.youtube.com/watch?v=WoDSPlUY7AM', '2024-04-01 22:00:00', './music/Neco Arc - Hand Of Blood (AI Cover)-FliKer.opus', 0, 212),
(543, 'Neco Arc - Life is A Highway (Rascal Flatts AI Cover)', 'tuyoki', 'https://www.youtube.com/@tuyoki.', 'https://www.youtube.com/watch?v=sty0yJMVLKI', '2024-04-01 22:00:00', './music/Neco Arc - Life is A Highway (Rascal Flatts AI Cover)-tuyoki.opus', 0, 276),
(544, 'Neco Arc - Miss Kobayashis Neco Arc Maid OP (AI COVER)', 'Дима Mojong', 'https://www.youtube.com/@TheMojongChannel', 'https://www.youtube.com/watch?v=vDyF2hpZzvU', '2024-04-01 22:00:00', './music/Neco Arc - Miss Kobayashis Neco Arc Maid OP (AI COVER)-Дима Mojong.opus', 0, 90),
(545, 'Neco Arc - Not Ready to Die (AI Cover)', 'sawlaseesee', 'https://www.youtube.com/@sawlaseesee', 'https://www.youtube.com/watch?v=Tw5UkFEqPzE', '2024-04-01 22:00:00', './music/Neco Arc - Not Ready to Die (AI Cover)-sawlaseesee.opus', 0, 425),
(546, 'Neco Arc - Nyubody (AI Cover)', 'tyronestash', 'https://www.youtube.com/@tyronestash', 'https://www.youtube.com/watch?v=wYg822_AQew', '2024-04-01 22:00:00', './music/Neco Arc - Nyubody (AI Cover)-tyronestash.opus', 0, 236),
(547, 'Neco Arc - One Way Or Another (Blondie AI Cover)', 'ScorchedCube', 'https://www.youtube.com/@ScorchedCube', 'https://www.youtube.com/watch?v=2y_Vnv-BIfo', '2024-04-01 22:00:00', './music/Neco Arc - One Way Or Another (Blondie AI Cover)-ScorchedCube.opus', 0, 214),
(548, 'Neco Arc - Over the Rainbow (AI Cover)', 'figas', 'https://www.youtube.com/@figas126', 'https://www.youtube.com/watch?v=2Cg4kZgxpSc', '2024-04-01 22:00:00', './music/Neco Arc - Over the Rainbow (AI Cover)-figas.opus', 0, 212),
(549, 'Neco arc - Replay', 'MugsNeko', 'https://www.youtube.com/@MugsNiko_MugsNeko', 'https://www.youtube.com/watch?v=evn-rQmkLhM', '2024-04-01 22:00:00', './music/Neco arc - Replay-MugsNeko.opus', 0, 183),
(550, 'Neco Arc — Scavenger (Ai Cover)', 'Interlocutor Grey', 'https://www.youtube.com/@interlocutorgrey8972', 'https://www.youtube.com/watch?v=ON6t33EQsqM', '2024-04-01 22:00:00', './music/Neco Arc — Scavenger (Ai Cover)-Interlocutor Grey.opus', 0, 157),
(551, 'Neco Arc - Smells Like Teen Spirit [A.I. Cover]', 'La-Creatura', 'https://www.youtube.com/@La-Creatura', 'https://www.youtube.com/watch?v=dm4A6Vz6pB0', '2024-04-01 22:00:00', './music/Neco Arc - Smells Like Teen Spirit [A.I. Cover]-La-Creatura.opus', 0, 301),
(552, 'Neco Arc - Stayin Alive (Neco Arc Ai Cover)', 'FliKer', 'https://www.youtube.com/@fl1ktm', 'https://www.youtube.com/watch?v=UJnXVE1lFdQ', '2024-04-01 22:00:00', './music/Neco Arc - Stayin Alive (Neco Arc Ai Cover)-FliKer.opus', 0, 250),
(553, 'Neco Arc - Survivor - Eye Of The Tiger (AI Cover)', 'rsdelta', 'https://www.youtube.com/@rsdelta', 'https://www.youtube.com/watch?v=6bKaw0zZqP4', '2024-04-01 22:00:00', './music/Neco Arc - Survivor - Eye Of The Tiger (AI Cover)-rsdelta.opus', 0, 245),
(554, 'Neco Arc - The Bad Touch (Bloodhound Gang) AI Cover', 'ScorchedCube', 'https://www.youtube.com/@ScorchedCube', 'https://www.youtube.com/watch?v=O1tk9obfi7o', '2024-04-01 22:00:00', './music/Neco Arc - The Bad Touch (Bloodhound Gang) AI Cover-ScorchedCube.opus', 0, 261),
(555, 'Neco Arc - The Real Slim Shady', 'Savtera gayming', 'https://www.youtube.com/@cumlord69', 'https://www.youtube.com/watch?v=yBjyLR9PIRo', '2024-04-01 22:00:00', './music/Neco Arc - The Real Slim Shady-Savtera gayming.opus', 0, 285),
(556, 'Neco arc - West Virginia (AI Cover) [REUPLOAD]', 'AntYey', 'https://www.youtube.com/@antyey', 'https://www.youtube.com/watch?v=44uS3zostg0', '2024-04-01 22:00:00', './music/Neco arc - West Virginia (AI Cover) [REUPLOAD]-AntYey.opus', 0, 196),
(557, 'Neco Arc - Виктор Цой - Звезда По Имени Солнце (AI Cover)', 'rsdelta', 'https://www.youtube.com/@rsdelta', 'https://www.youtube.com/watch?v=vl0-OTzQTy8', '2024-04-01 22:00:00', './music/Neco Arc - Виктор Цой - Звезда По Имени Солнце (AI Cover)-rsdelta.opus', 0, 225),
(558, 'Neco Arc - Возьми мое сердце (AI COVER)', 'Дима Mojong', 'https://www.youtube.com/@TheMojongChannel', 'https://www.youtube.com/watch?v=tYMNzsecec4', '2024-04-01 22:00:00', './music/Neco Arc - Возьми мое сердце (AI COVER)-Дима Mojong.opus', 0, 246),
(559, 'Neco Arc - Когда я стану кошкой (AI COVER)', 'Дима Mojong', 'https://www.youtube.com/@TheMojongChannel', 'https://www.youtube.com/watch?v=43rfNGA4FvE', '2024-04-01 22:00:00', './music/Neco Arc - Когда я стану кошкой (AI COVER)-Дима Mojong.opus', 0, 205),
(560, 'Neco arc - Луч солнца золотого (ai cover)', 'Вячеслав Подъяблонский', 'https://www.youtube.com/@Xunnu2', 'https://www.youtube.com/watch?v=acJIC_2Vyi0', '2024-04-01 22:00:00', './music/Neco arc - Луч солнца золотого (ai cover)-Вячеслав Подъяблонский.opus', 0, 156),
(561, 'Neco Arc - Облака белогривые лошадки (AI cover)', 'HIDDEN', 'https://www.youtube.com/@hidden457', 'https://www.youtube.com/watch?v=kGQ1UOVGpFc', '2024-04-01 22:00:00', './music/Neco Arc - Облака белогривые лошадки (AI cover)-HIDDEN.opus', 0, 161),
(562, 'Neco Arc - Пойдем со мной (AI COVER)', 'Дима Mojong', 'https://www.youtube.com/@TheMojongChannel', 'https://www.youtube.com/watch?v=1h8axBqWt2E', '2024-04-01 22:00:00', './music/Neco Arc - Пойдем со мной (AI COVER)-Дима Mojong.opus', 0, 105),
(563, 'Neco Arc - ПОТЕРЯННЫЙ РАЙ (AI COVER)', 'Дима Mojong', 'https://www.youtube.com/@TheMojongChannel', 'https://www.youtube.com/watch?v=pB6P28rHego', '2024-04-01 22:00:00', './music/Neco Arc - ПОТЕРЯННЫЙ РАЙ (AI COVER)-Дима Mojong.opus', 0, 353),
(564, 'Король и Шут - Кукла Колдуна (кукла burunya) (AI cover)', 'Toffee ツ', 'https://www.youtube.com/@Toffeechka', 'https://www.youtube.com/watch?v=BQFDmkaHeic', '2024-04-01 22:00:00', './music/Король и Шут - Кукла Колдуна (кукла burunya) (AI cover)-Toffee ツ.opus', 0, 202),
(565, 'neco arc sing never be alone (AI Cover)', 'Sokar', 'https://www.youtube.com/@MentalIllBoy', 'https://www.youtube.com/watch?v=g36Bb4nqQZs', '2024-04-01 22:00:00', './music/neco arc sing never be alone (AI Cover)-Sokar.opus', 0, 178),
(566, 'Neco arc sings Another one bites the dust (Ai cover)', 'Neco Chaos', 'https://www.youtube.com/@NecoChaos_fan', 'https://www.youtube.com/watch?v=C0Q3HNGJhEk', '2024-04-01 22:00:00', './music/Neco arc sings Another one bites the dust (Ai cover)-Neco Chaos.opus', 0, 215),
(567, 'Neco arc sings Hearts On Fire (Ai cover)', 'Neco Chaos', 'https://www.youtube.com/@NecoChaos_fan', 'https://www.youtube.com/watch?v=CejZHDYtaOU', '2024-04-01 22:00:00', './music/Neco arc sings Hearts On Fire (Ai cover)-Neco Chaos.opus', 0, 232),
(568, 'Neco arc sings Lay All Your Love On Me (Ai cover)', 'Neco Chaos', 'https://www.youtube.com/@NecoChaos_fan', 'https://www.youtube.com/watch?v=ZIqyDblD8Ps', '2024-04-01 22:00:00', './music/Neco arc sings Lay All Your Love On Me (Ai cover)-Neco Chaos.opus', 0, 290),
(569, 'Смяульчак и ветер || Король и Шут - Смельчак и ветер Neco-Arc (AI Cover)', 'MaxwellHUB', 'https://www.youtube.com/@MaxwellHUB1', 'https://www.youtube.com/watch?v=1ZJF-pYyXCY', '2024-04-01 22:00:00', './music/Смяульчак и ветер || Король и Шут - Смельчак и ветер Neco-Arc (AI Cover)-MaxwellHUB.opus', 0, 178),
(570, 'Neco-Arc - Wait and Bleed (ai cover Slipknot)', 'otakuyu!', 'https://www.youtube.com/@otakuyu', 'https://www.youtube.com/watch?v=jAun1BoFaks', '2024-04-01 22:00:00', './music/Neco-Arc - Wait and Bleed (ai cover Slipknot)-otakuyu!.opus', 0, 149),
(571, 'Neco-Arc sings \"Your Reality\"', 'l1minal', 'https://www.youtube.com/@l1minal541', 'https://www.youtube.com/watch?v=0sYQ3OyWOHQ', '2024-04-01 22:00:00', './music/Neco-Arc sings \"Your Reality\"-l1minal.opus', 0, 181),
(572, 'Некомант || Король и Шут - Некромант Neco-Arc (AI Cover)', 'MaxwellHUB', 'https://www.youtube.com/@MaxwellHUB1', 'https://www.youtube.com/watch?v=W9t4N7hlmf0', '2024-04-01 22:00:00', './music/Некомант || Король и Шут - Некромант Neco-Arc (AI Cover)-MaxwellHUB.opus', 0, 161),
(573, 'No Doubt - Dont Speak  (Neco arc Ai cover)', 'H.D.P.L.', 'https://www.youtube.com/@H.D.P.L.', 'https://www.youtube.com/watch?v=p6Vz43t_QKo', '2024-04-01 22:00:00', './music/No Doubt - Dont Speak  (Neco arc Ai cover)-H.D.P.L..opus', 0, 262),
(574, 'Rob Zombie - Dragula  (Neco arc Ai cover)', 'H.D.P.L.', 'https://www.youtube.com/@H.D.P.L.', 'https://www.youtube.com/watch?v=2iGxFyT0lzM', '2024-04-01 22:00:00', './music/Rob Zombie - Dragula  (Neco arc Ai cover)-H.D.P.L..opus', 0, 228),
(575, 'Утренний буранья || Король и Шут - Утренний рассвет Neco-Arc (AI Cover)', 'MaxwellHUB', 'https://www.youtube.com/@MaxwellHUB1', 'https://www.youtube.com/watch?v=f4vcrl6z5Ps', '2024-04-01 22:00:00', './music/Утренний буранья || Король и Шут - Утренний рассвет Neco-Arc (AI Cover)-MaxwellHUB.opus', 0, 148),
(576, 'Coming Undone - Neco Arc cover (KoRn)', 'Edward Moreno', 'https://www.youtube.com/@edwardmoreno6468', 'https://www.youtube.com/watch?v=uYSIQQixaMw', '2024-04-01 22:00:00', './music/Coming Undone - Neco Arc cover (KoRn)-Edward Moreno.opus', 0, 200),
(577, 'Neco Arc - Feel good inc (Gorillaz Ai cover)', 'Exaton', 'https://www.youtube.com/@Exaton_music', 'https://www.youtube.com/watch?v=BUHFi7uwsBA', '2024-04-01 22:00:00', './music/Neco Arc - Feel good inc (Gorillaz Ai cover)-Exaton.opus', 0, 222),
(578, 'Neco-Arc – Have You Ever Seen The Rain (Creedence Clearwater Revival AI Cover)', 'NECO', 'https://www.youtube.com/@NECO2926', 'https://www.youtube.com/watch?v=W-qjpBG7aoA', '2024-04-01 22:00:00', './music/Neco-Arc – Have You Ever Seen The Rain (Creedence Clearwater Revival AI Cover)-NECO.opus', 0, 160),
(579, 'Neco Arc - Hell Is For Children (Pat Benatar) AI Cover', 'ScorchedCube', 'https://www.youtube.com/@ScorchedCube', 'https://www.youtube.com/watch?v=90qtXzP18c0', '2024-04-01 22:00:00', './music/Neco Arc - Hell Is For Children (Pat Benatar) AI Cover-ScorchedCube.opus', 0, 291),
(580, 'Neco Arc - Jingle Bell Rock [AI Cover]', 'Vern Von Trertnert', 'https://www.youtube.com/@Vern_Von_Trertnert', 'https://www.youtube.com/watch?v=E_u5AGzuHy0', '2024-04-01 22:00:00', './music/Neco Arc - Jingle Bell Rock [AI Cover]-Vern Von Trertnert.opus', 0, 195),
(581, 'Neco Arc - Take On Me (AI Cover)', 'Manakarc the Insane', 'https://www.youtube.com/@ManakarctheInsane', 'https://www.youtube.com/watch?v=lqsVdOHiRPg', '2024-04-01 22:00:00', './music/Neco Arc - Take On Me (AI Cover)-Manakarc the Insane.opus', 0, 225),
(582, 'Neco Arc - What Is Love (AI Cover)', 'Manakarc the Insane', 'https://www.youtube.com/@ManakarctheInsane', 'https://www.youtube.com/watch?v=gpNmnj3ss2M', '2024-04-01 22:00:00', './music/Neco Arc - What Is Love (AI Cover)-Manakarc the Insane.opus', 0, 266),
(583, 'Neco Arc - Zombie (The Cranberries) AI Cover', 'ScorchedCube', 'https://www.youtube.com/@ScorchedCube', 'https://www.youtube.com/watch?v=Z2PZ8mDGpxU', '2024-04-01 22:00:00', './music/Neco Arc - Zombie (The Cranberries) AI Cover-ScorchedCube.opus', 0, 306),
(584, 'Neco Arc - Проклятый старый дом (AI COVER)', 'Дима Mojong', 'https://www.youtube.com/@TheMojongChannel', 'https://www.youtube.com/watch?v=YH9OLddlkfs', '2024-04-01 22:00:00', './music/Neco Arc - Проклятый старый дом (AI COVER)-Дима Mojong.opus', 0, 257),
(585, 'Neco Arc sings \"I Got No Time\" but the part that SHOULD HAVE BEEN AN INSTRUMENTAL is an instrumental', 'Yeko', 'https://www.youtube.com/@yekothereaper', 'https://www.youtube.com/watch?v=dQ1XXkQqNU0', '2024-04-01 22:00:00', './music/Neco Arc sings \"I Got No Time\" but the part that SHOULD HAVE BEEN AN INSTRUMENTAL is an instrumental-Yeko.opus', 0, 181),
(586, 'Neco Arc Wants You To Do Right', 'Coffeechipmunk', 'https://www.youtube.com/@Coffeechipmunk', 'https://www.youtube.com/watch?v=eoMWSPxFCnw', '2024-04-01 22:00:00', './music/Neco Arc Wants You To Do Right-Coffeechipmunk.opus', 0, 160),
(587, 'Neco-Arc - Killing In the Name (ai cover Rage Against The Machine)', 'otakuyu!', 'https://www.youtube.com/@otakuyu', 'https://www.youtube.com/watch?v=Ss_y6onuzJw', '2024-04-01 22:00:00', './music/Neco-Arc - Killing In the Name (ai cover Rage Against The Machine)-otakuyu!.opus', 0, 313),
(588, 'Neco-Arc - Dance, Dance (ai cover Fall Out Boy)', 'otakuyu!', 'https://www.youtube.com/@otakuyu', 'https://www.youtube.com/watch?v=afe5m4hJ8t4', '2024-04-01 22:00:00', './music/Neco-Arc - Dance, Dance (ai cover Fall Out Boy)-otakuyu!.opus', 0, 179),
(589, 'Neco-Arc - Give It Away (ai cover Red Hot Chili Peppers)', 'otakuyu!', 'https://www.youtube.com/@otakuyu', 'https://www.youtube.com/watch?v=a39yJW0UPPA', '2024-04-01 22:00:00', './music/Neco-Arc - Give It Away (ai cover Red Hot Chili Peppers)-otakuyu!.opus', 0, 287),
(590, 'Neco-Arc - Psychosocial (ai cover Slipknot)', 'otakuyu!', 'https://www.youtube.com/@otakuyu', 'https://www.youtube.com/watch?v=o-uIu2pSxNA', '2024-04-01 22:00:00', './music/Neco-Arc - Psychosocial (ai cover Slipknot)-otakuyu!.opus', 0, 281),
(591, 'Neco-Arc - Square Hammer (ai cover Ghost)', 'otakuyu!', 'https://www.youtube.com/@otakuyu', 'https://www.youtube.com/watch?v=Q1ekjBWCHok', '2024-04-01 22:00:00', './music/Neco-Arc - Square Hammer (ai cover Ghost)-otakuyu!.opus', 0, 237),
(592, 'Neco-Arc - Wonderwall (ai cover Oasis)', 'otakuyu!', 'https://www.youtube.com/@otakuyu', 'https://www.youtube.com/watch?v=J5B6SX9ZJb0', '2024-04-01 22:00:00', './music/Neco-Arc - Wonderwall (ai cover Oasis)-otakuyu!.opus', 0, 259),
(593, 'Static X - The Only (Neco Arc AI Cover)', 'hunty', 'https://www.youtube.com/@denikec', 'https://www.youtube.com/watch?v=0umlcrIo-S4', '2024-04-01 22:00:00', './music/Static X - The Only (Neco Arc AI Cover)-hunty.opus', 0, 171),
(594, 'the hand that feeds by nine inch nails but its neco arc', 'the troll', 'https://www.youtube.com/@thetroll3284', 'https://www.youtube.com/watch?v=Mw0KEv13TfU', '2024-04-01 22:00:00', './music/the hand that feeds by nine inch nails but its neco arc-the troll.opus', 0, 214),
(595, 'Melty Blood Type Lumina OST - Great Cats Village R (Neco-Arcs Theme)', 'HGhaleon', 'https://www.youtube.com/@HGhaleon', 'https://www.youtube.com/watch?v=wcpQ3aarHRU', '2024-04-01 22:00:00', './music/Melty Blood Type Lumina OST - Great Cats Village R (Neco-Arcs Theme)-HGhaleon.opus', 0, 241);

--
-- Index för dumpade tabeller
--

--
-- Index för tabell `music`
--
ALTER TABLE `music`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT för dumpade tabeller
--

--
-- AUTO_INCREMENT för tabell `music`
--
ALTER TABLE `music`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=596;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
